apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node. 
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config-pvc
spec:
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node. 
  resources:
    requests:
      storage: 100Mi