apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    app: mosquitto 
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    listener 8883
    cafile /mosquitto/config/certs/ca.crt
    certfile /mosquitto/config/certs/server.crt
    keyfile /mosquitto/config/certs/server.key
    allow_anonymous true
